const APP = import('../pages/app.vue')
const APP__ID = import('../pages/app/_id.vue')
const HOME = import('../pages/home.vue')
const HOME_LIST = import('../pages/home/list.vue')
const HOME_LIST_DATA = import('../pages/home/list/data.vue')
const HOME_LIST_DATA_USER = import('../pages/home/list/data/user.vue')
const LOGIN = import('../pages/login.vue')
const WEEX = import('../pages/weex.vue')
